name: export
on:
  workflow_dispatch:
  #push:
    #paths:
      #- '**.svg'

jobs:
  export:
    runs-on: ubuntu-latest
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    - uses: actions/checkout@v3

    - name: setup dependencies
      run: |
        sudo apt-get install -y inkscape 
        sudo apt-get -y install tree 
        sudo apt-get install -y resvg
    - name: run bash
      run: bash ./export.sh

    - name: debug
      run: tree

    - name: upload a artifact
      uses: actions/upload-artifact@v3.0.0
      with:
        name: render
        path: ./render
