name: export
on:
  workflow_dispatch:
  push:
    paths:
      - '**.svg'

jobs:
  export:
    runs-on: ubuntu-latest
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    - uses: actions/checkout@v3

    - name: setup inkscape
      run: sudo apt-get install -y inkscape

    - name: py setup
      uses: actions/setup-python@v3
      with:
        python-version: "3.8"

    - name: run py
      run: python ${GITHUB_WORKSPACE}/export.py

    - name: zip artifacts
      run: tar -zcvf render.tar.gz ${GITHUB_WORKSPACE}/render/

    - name: upload a artifact
      uses: actions/upload-artifact@v3.0.0
      with:
        name: render
      path: ${GITHUB_WORKSPACE}/render.tar.gz