name: export
on:
  workflow_dispatch:
  push:
    paths:
      - '**.svg'

jobs:
  export:
    runs-on: ubuntu-latest
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    - uses: actions/checkout@v3

    - name: setup dependencies
      run: |
        sudo apt-get install -y inkscape 
        sudo apt-get -y install tree 
        wget https://github.com/RazrFalcon/resvg/releases/download/v0.22.0/resvg-linux-x86_64.tar.gz -O resvg.tar.gz
        tar xvf resvg.tar.gz
        rm -f resvg.tar.gz
      
    - name: run bash
      run: bash ./export.sh

    - name: debug
      run: tree

    - name: upload a artifact
      uses: actions/upload-artifact@v3.0.0
      with:
        name: sprites-override
        path: ./sprites-override
