name: export
on:
  workflow_dispatch:
  push:
    paths:
      - '**.svg'

jobs:
  export:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: setup dependencies
      run: |
        sudo apt-get install -y inkscape 
        sudo apt-get -y install tree 
        wget https://github.com/RazrFalcon/resvg/releases/download/v0.22.0/resvg-linux-x86_64.tar.gz -O resvg.tar.gz
        tar xvf resvg.tar.gz
      
    - name: run bash
      run: bash ./export.sh && tree
      
    - name: prepare artifact
      run: find . -maxdepth 1 -not -name 'sprites-override' -not -name 'mod.*' -not -name 'README.md' -exec /bin/rm -rf '{}' \; && tree 
      # delete everything but mod.hjson, readme, and sprites

    - name: upload a artifact
      uses: actions/upload-artifact@v3.0.0
      with:
        name: mod
        path: .
