name: export
on:
  workflow_dispatch:
  push:
    branches:
      - "main"
    paths:
      - "**.svg"

jobs:
  export:
    runs-on: ubuntu-latest
    steps:
      - uses: hortiSquash/hortiDefinition/.github/actions/export@main
