name: "release"
on:
  workflow_dispatch:
  push: 
    tags:
      - 'v*'
    

# copy over export.yml: look into better method
jobs:
  release:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: setup dependencies
      run: |
        sudo apt-get -y install tree 
        wget https://github.com/RazrFalcon/resvg/releases/download/v0.22.0/resvg-linux-x86_64.tar.gz -O resvg.tar.gz
        tar xvf resvg.tar.gz
      
    - name: prepare python for math 
      uses: actions/setup-python@v2
      with:
        python-version: '3.9'
        # cache: 'pip'
      
    - name: run bash
      run: |
        bash ./prepare-artifact.sh .5
        bash ./prepare-artifact.sh 2
        bash ./prepare-artifact.sh 4
      
    - name: release
      uses: ncipollo/release-action@v1
      with:
        artifacts: "*.zip"
        bodyFile: changelog.md
        token: ${{ secrets.GITHUB_TOKEN }}
