name: "release"
on:
  push:
    branches: [main]
    paths:
      - _src_/*/**.svg # dont match toplevel _src_ items, eg template.svg
      - .github/**.yml

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  changelog:
    outputs:
      version: ${{ steps.changelog.outputs.version }}
      body: ${{ steps.changelog.outputs.clean_changelog }}
      tag: ${{ steps.changelog.outputs.tag }}
      skipped: ${{ steps.changelog.outputs.skipped }}

    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v3
        # with:
        #   lfs: true

      - name: create changelog
        id: changelog
        uses: TriPSs/conventional-changelog-action@v3
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          skip-version-file: "true"
          skip-on-empty: "true"
          output-file: "false"
          skip-commit: "true"

  release:
    needs: changelog
    runs-on: ubuntu-latest
    if: ${{ needs.changelog.outputs.skipped == 'false' }}
    steps:
      - uses: actions/checkout@v3
        with:
          lfs: true

      - name: get moreutils
        run: sudo apt-get update && sudo apt-get install -y moreutils

      - name: set version
        run: jq '.version = "${{ needs.changelog.outputs.tag }}"' mod.json | sponge mod.json

      - name: make artifacts
        uses: hortiSquash/hortiDefinition/.github/actions/export@main

      - name: tag head
        run: git tag ${{ needs.changelog.outputs.tag }}

      - name: release
        uses: ncipollo/release-action@v1.10.0
        with:
          artifacts: "**.zip"
          body: ${{ needs.changelog.outputs.body }}
          tag: ${{ needs.changelog.outputs.tag }}
