name: "release"
on:
  push:
    tags:
      - "v*"

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: export
        uses: hortiSquash/hortiDefinition/.github/actions/export@main

      - name: release
        uses: ncipollo/release-action@v1
        with:
          artifacts: "**.zip"
          bodyFile: changelog.md
          token: ${{ secrets.GITHUB_TOKEN }}
