name: "release"
on:
  push:
    branches: [main]
    paths:
      - _src_/*/**.svg # dont match toplevel _src_ items, eg template.svg
      - ./.github/workflows/release.yml
      - ./export.sh
      - ./outline.py
      - ./prepare-artifact.sh
      - ./mod.json
      - ./manual_outline
      - ./requirements.txt
      - ./trim.py
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  changelog:
    outputs:
      version: ${{ steps.changelog.outputs.version }}
      body: ${{ steps.changelog.outputs.clean_changelog }}
      tag: ${{ steps.changelog.outputs.tag }}
      skipped: ${{ steps.changelog.outputs.skipped }}

    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v3
        # with:
        #   lfs: true

      - name: create changelog
        id: changelog
        uses: TriPSs/conventional-changelog-action@v3
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          skip-version-file: "true"
          skip-on-empty: "true"
          output-file: "false"
          skip-commit: "true"

  release:
    needs: changelog
    runs-on: ubuntu-latest
    if: ${{ needs.changelog.outputs.skipped == 'false' }}
    steps:
      - uses: actions/checkout@v3
        with:
          lfs: true
          fetch-depth: 0

      - name: prepare python
        uses: actions/setup-python@v2
        with:
          python-version: "3.9"
          cache: "pip"

      - name: get dependencies
        run: |
          echo ::group::deps
          sudo apt-get update && sudo apt-get install -y moreutils tree imagemagick jq
          wget -nv https://github.com/RazrFalcon/resvg/releases/download/v0.23.0/resvg-linux-x86_64.tar.gz -O resvg.tar.gz
          tar xvf resvg.tar.gz
          sudo mv resvg /usr/bin
          pip install -r requirements.txt
          echo ::endgroup::

      - name: set mod version
        run: jq '.version = "${{ needs.changelog.outputs.tag }}"' mod.json | sponge mod.json

      - name: make artifacts
        run: |
          ./prepare-artifact.sh 0.25
          ./prepare-artifact.sh 0.5
          ./prepare-artifact.sh 1
          ./prepare-artifact.sh 2
          ./prepare-artifact.sh 4
          ./prepare-artifact.sh 8

      - name: create tag
        run: git tag ${{ needs.changelog.outputs.tag }}

      - name: upload artifacts
        uses: actions/upload-artifact@v3.0.0
        with:
          path: "**.zip"

      - name: release artifacts
        uses: ncipollo/release-action@v1.10.0
        with:
          artifacts: "**.zip"
          body: ${{ needs.changelog.outputs.body }}
          tag: ${{ needs.changelog.outputs.tag }}
